# Generated by Django 6.0.5 on 2026-05-11 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('task_claimed', 'Your task was claimed'), ('flash_gig', 'Flash-Gig nearby'), ('rating_request', 'You have a rating to submit'), ('vouch_received', 'Someone vouched for you'), ('general', 'General')], max_length=20, verbose_name='kind')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('body', models.TextField(blank=True, max_length=300, verbose_name='body')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
