# Generated by Django 6.0.5 on 2026-05-11 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hustles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouch',
            name='task',
            field=models.ForeignKey(help_text='The completed task that enables this vouch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouches', to='hustles.task', verbose_name='task'),
        ),
        migrations.AddField(
            model_name='vouch',
            name='vouchee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouches_received', to=settings.AUTH_USER_MODEL, verbose_name='vouchee'),
        ),
        migrations.AddField(
            model_name='vouch',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouches_given', to=settings.AUTH_USER_MODEL, verbose_name='voucher'),
        ),
        migrations.AlterUniqueTogether(
            name='vouch',
            unique_together={('voucher', 'vouchee')},
        ),
    ]
