# Generated by Django 6.0.5 on 2026-05-11 23:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('category', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical'), ('delivery', 'Delivery'), ('event', 'Event'), ('other', 'Other')], default='other', max_length=20, verbose_name='category')),
                ('pay', models.DecimalField(decimal_places=0, help_text='Amount in CFA Francs (XAF).', max_digits=10, verbose_name='pay (XAF)')),
                ('required_people', models.PositiveSmallIntegerField(default=1, help_text='Set > 1 to enable Squad Up mode.', verbose_name='required people')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Exact GPS point. Kept private until task is claimed.', srid=4326, verbose_name='exact location')),
                ('location_approx', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Fuzzed location shown on the public map.', null=True, srid=4326, verbose_name='approximate location')),
                ('neighborhood', models.CharField(blank=True, help_text='Human-readable area name (e.g. Bastos, Molyko).', max_length=100, verbose_name='neighborhood')),
                ('is_flash_gig', models.BooleanField(default=False, help_text='If true, task expires after 15 minutes and nearby users are notified immediately.', verbose_name='flash-gig')),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=15, verbose_name='status')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('claimer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='claimer')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_tasks', to=settings.AUTH_USER_MODEL, verbose_name='poster')),
                ('squad_members', models.ManyToManyField(blank=True, related_name='squad_tasks', to=settings.AUTH_USER_MODEL, verbose_name='squad members')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 (worst) to 5 (best).', verbose_name='score')),
                ('comment', models.TextField(blank=True, max_length=280, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL, verbose_name='ratee')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='rater')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='hustles.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'rating',
                'verbose_name_plural': 'ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'expires_at'], name='hustles_tas_status_e3add3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category', 'status'], name='hustles_tas_categor_b820f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('task', 'rater', 'ratee')},
        ),
    ]
