# Generated by Django 6.0.5 on 2026-05-22 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='claimer_marked_complete_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='claimer marked complete at'),
        ),
        migrations.AddField(
            model_name='task',
            name='poster_marked_complete_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='poster marked complete at'),
        ),
        migrations.CreateModel(
            name='TaskApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=180, verbose_name='note')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=15, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_applications', to=settings.AUTH_USER_MODEL, verbose_name='applicant')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hustles.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task application',
                'verbose_name_plural': 'task applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'status'], name='hustles_tas_task_id_b88225_idx'), models.Index(fields=['applicant', 'status'], name='hustles_tas_applica_f52f52_idx')],
                'unique_together': {('task', 'applicant')},
            },
        ),
    ]
